version: '3'
services:
  cocktailbot-redis:
    image: redis:7.0
    hostname: localhost
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cocktailbot-redis:/data
    networks:
      - cocktailbot-network
    container_name: cocktailbot-redis

  cocktailbot-app:
    image: cocktail-bot:1.0
    environment:
      REDIS_URL: redis://redis:6379/0
      COCKTAILBOT_TOKEN:
    depends_on:
      - cocktailbot-redis
    networks:
      - cocktailbot-network
    container_name: cocktailbot-app

networks:
  cocktailbot-network:

volumes:
  cocktailbot-redis:

#docker-compose up